[basic info]
testsiteurl=https://opensource-demo.orangehrmlive.com/

[Locators]
# Common locators
pageTitle_XPATH = //h6[contains(@class,'oxd-topbar-header-breadcrumb-module')]
userMenu_XPATH = //span[contains(@class,'oxd-userdropdown-tab')]
logout_XPATH = //a[contains(., 'Logout')]

# Login page locators
username_NAME = username
password_NAME = password
loginButton_XPATH = //button[@type='submit']
invalidLoginMessage_XPATH = //p[contains(., 'Invalid credentials')]

# Dashboard page locators
menuLink_XPATH = //a[.//span[normalize-space()='{module}']]

# Admin page locators
admin_search_userName_XPATH = //label[contains(., 'Username')]/..//following-sibling::div//input
admin_submit_Button_XPATH = .//button[@type='submit' and normalize-space()='Search']
admin_table_XPATH = .//div[@role='table']
admin_table_headers_XPATH = .//div[@role='columnheader']
admin_table_rows_XPATH = .//div[@role='row']
admin_table_cells_XPATH = .//div[@role='cell']
user_row_XPATH = //div[@role='row']//div[@role='cell' and normalize-space()='{username}']/ancestor::div[@role='row']

# Directory page locators

# Claim page locators

